### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stderr' of undefined

### ISSUE THREAD

**Issue by basheps** [danielbrodin/atom-open-in#3]
[Enter steps to reproduce below:]

1. Attempted to open directory instead of file by selected directory in sidebar
2. Open file in 'iTerm'

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.1
**Thrown From**: [open-in](https://github.com/danielbrodin/atom-open-in) package, v3.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'stderr' of undefined

```
At /Users/basheps/.atom/packages/open-in/lib/open-in-app-view.coffee:51

TypeError: Cannot read property 'stderr' of undefined
  at OpenInAppView.module.exports.OpenInAppView.confirmed (/Users/basheps/.atom/packages/open-in/lib/open-in-app-view.coffee:51:9)
  at OpenInAppView.confirmed (/Users/basheps/.atom/packages/open-in/lib/open-in-app-view.coffee:1:1)
  at OpenInAppView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/src/select-list-view.js:331:21)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/select-list-view.js:113:24)
  at HTMLDivElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -3:21.2 core:confirm (atom-text-editor.editor.mini)
     -3:11.2 open-in:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:05.4 core:confirm (atom-text-editor.editor.mini)
     -2:35.9 settings-view:open (atom-pane.pane.active)
     -2:04.8 core:backspace (atom-text-editor#open-in.applications.editor.mini)
     -1:31.6 core:confirm (atom-text-editor#open-in.applications.editor.mini)
     -1:15.7 open-in:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -1:12.5 core:confirm (atom-text-editor.editor.mini)
     -0:43.1 open-in:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:41.5 core:confirm (atom-text-editor.editor.mini)
     -0:24.7 open-in:toggle (atom-text-editor.editor)
     -0:21.1 core:move-down (atom-text-editor.editor.mini)
  2x -0:19.3 core:confirm (atom-text-editor.editor.mini)
     -0:02.6 open-in:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.8 core:move-down (atom-text-editor.editor.mini)
  2x -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "open-in": {
    "applications": "iTerm, Terminal, Chrome"
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.4.0
atom-terminal, v0.6.0
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
color-picker, v1.4.4
dart-tools, v0.8.5
emmet, v2.3.2
go-plus, v3.0.13
language-dart, v0.1.1
language-jade, v0.3.0
linter, v0.10.0
linter-dartanalyzer, v0.3.1
open-in, v3.1.0
preview-plus, v1.1.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by manikanta443** [comment]
hai , i m facing same problem , did u find solution for that .

Thanks in advance
