### ISSUE TITLE
Failed to activate the open-in package

### ISSUE THREAD

**Issue by edzis** [danielbrodin/atom-open-in#6]
[Enter steps to reproduce below:]

1. Fresh install
2. Toggle

**Atom Version**: 0.209.0
**System**: Mac OS X 10.9.5
**Thrown From**: [open-in](https://github.com/danielbrodin/atom-open-in) package, v3.1.0

### Stack Trace

Failed to activate the open-in package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/edgar/.atom/packages/open-in/lib/open-in.coffee:8:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -5:04.6.0 core:paste (atom-text-editor.editor.is-focused)
     -5:03.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:01.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:01.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -5:00.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:00.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:59.1.0 core:undo (atom-text-editor.editor.is-focused)
  2x -4:58 core:backspace (atom-text-editor.editor.is-focused)
     -4:54.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:16.8.0 tree-view:copy (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:02.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:43.5.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -1:40.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:26.1.0 core:close (atom-text-editor.editor.is-focused)
     -1:09.6.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:01.7.0 open-in:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jshint",
      "sourcegraph-atom",
      "linter-js-standard",
      "linter"
    ]
  }
}
```

### Installed Packages

```coffee
# User
jshint, v1.3.7
language-svg, v0.8.0
open-in, v3.1.0
svg-preview, v0.6.0

# Dev
No dev packages
```

**Comment by purplespider** [comment]
Same issue here. Not working on latest Atom verison.

**Comment by danielbrodin** [comment]
A new version have been released that should work.
